### ISSUE TITLE
Clarification on evaluation protocol

### ISSUE THREAD

**Issue by winston-zillow** [Hypatiaalegra/LogicGame-Data#1]
In the paper, it said,

> Process Accuracy(P-Acc): This metric assesses the correctness of the process, measuring
the percentage match based on character-level similarity between the provided process and
the expected process

My understanding is that the process is the plan the LLM comes up arrive the solution. 

1. Are all tasks in the dataset guaranteed to have only one correct process?
2. Are the outputs normalized before evaluating character-level similarity? Can you provide the code snippets used?
3. I noticed that you also reported the IFError and JSError. In case of such mechanical errors, do you fix the outputs and proceed to evaluate the AP-Acc or you just mark those sample unit with 0 scores?

**Comment by Hypatiaalegra** [comment]
Thank you for raising these questions. Your understanding of the "process" as the plan an LLM uses to arrive at a solution is correct.
1. Yes,  we have specifically designed the tasks in the dataset and the output constrain to ensure that each task can only be solved correctly by following one exact process.
2. Yes, if by normalization you mean the parsing of the JSON format in the model's response. We detect the json section in the response and parse it into the correct JSON format for evaluation. 
3. No, we do not fix the outputs in cases of mechanical errors like IFError or JSError. These samples with mechanical errors are marked with 0 scores. This is because mechanical errors can manifest in various forms and sometimes there is no straightforward fix, which often requires extensive human intervention that is not feasible for us.

**Comment by winston-zillow** [comment]
> Yes, if by normalization you mean the parsing of the JSON format in the model's response. We detect the json section in the response and parse it into the correct JSON format for evaluation.

I get that the response JSON is extracted and parsed. But the answer fields are string values. Do you further normalize the string values?

> These samples with mechanical errors are marked with 0 scores.

While avoiding mechanical errors is a good thing, would this bias toward those models following instruction or formatting better rather than reasoning better? (for example, I heard that later verisons of gpt-4* was specifically improved for generating JSON.) As the goal is evaluate reasoning capability, it may be better to fix at least some of the errors (like the JSError) by human, as long as the fix guideline and fix rates are also reported.

**Comment by winston-zillow** [comment]
> character-level similarity

What is this done exactly? Also can you provide code snippets for the exact similarity measurement? Do you use edit distance?

If a process answer of length 100 inserts an extra character at the 6th position, then a left-to-right match would report only 5% accuracy whereas an edit-distance would report 99% match.

**Comment by Hypatiaalegra** [comment]
In your example, we utilize a left-to-right matching approach, resulting in an accuracy of 5%. This is because the reasoning chain progresses in a unidirectional manner from premise to conclusion, making an edit-distance approach inappropriate for this context.
Below is a code snippet demonstrating the measurement of similarity:
`process_match = sum(1 for m, r in zip(model_answer['process'], ref_answer['process']) if m == r) `
  `total_processes = len(ref_answer['process'])`
  `row['only_process_correct'] = round(process_match / total_processes,2)`
  
  The `only_process_correct` score is calculated based on character-level similarity.

**Comment by Hypatiaalegra** [comment]
In your example, we utilize a left-to-right matching approach, resulting in an accuracy of 5%. This calculation is based on the sequential nature of the reasoning chain, which progresses in a unidirectional manner from premise to conclusion. The left-to-right matching method aligns with this linear progression, ensuring that each step in the process is evaluated in its correct order. On the other hand, an edit-distance approach might not be well-suited for this specific context as it could potentially overestimate the accuracy by ignoring the importance of the order of intermediate steps.  
Below is a code snippet demonstrating the measurement of similarity: 
`process_match = sum(1 for m, r in zip(model_answer['process'], ref_answer['process']) if m == r)` 
`total_processes = len(ref_answer['process'])`
`row['only_process_correct'] = round(process_match / total_processes,2)`

The only_process_correct score is calculated based on character-level similarity.

**Comment by Hypatiaalegra** [comment]
> I get that the response JSON is extracted and parsed. But the answer fields are string values. Do you further normalize the string values?

The answer fields are required to be in list format, just like the process fields. The entire JSON is parsed and directly compared with the reference answer and process fields without any further normalization.

> While avoiding mechanical errors is a good thing, would this bias toward those models following instruction or formatting better rather than reasoning better? (for example, I heard that later verisons of gpt-4* was specifically improved for generating JSON.) As the goal is evaluate reasoning capability, it may be better to fix at least some of the errors (like the JSError) by human, as long as the fix guideline and fix rates are also reported.

Your idea is an inspiring one. Though there is a concern that some models might perform better solely due to their formatting precision, the incidence of JSError is relatively low, so the impact is minor. However, for errors related to following instructions, we are considering improving this part in future updates.

**Comment by Violettttee** [comment]
所以可以请问下具体的评估方法也是没有公开的吗？
